### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by zenzoa** [asdfman/linux-shimeji#22]
Would it be possible for this project to support Wayland compositors, like Hyprland or Sway? I tried running it anyway (in Hyprland) in case xwayland would get it working but I get these errors:

```
java.lang.IllegalAccessException: class com.sun.jna.platform.WindowUtils$X11WindowUtils cannot access class sun.awt.X11GraphicsConfig (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @50a638b5
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:420)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:709)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils.getVisualID(WindowUtils.java:1178)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils.getAlphaCompatibleGraphicsConfiguration(WindowUtils.java:1199)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils.setWindowTransparent(WindowUtils.java:1406)
	at com.sun.jna.platform.WindowUtils.setWindowTransparent(WindowUtils.java:1549)
	at com.group_finity.mascot.x11.X11TranslucentWindow.setVisible(Unknown Source)
	at com.group_finity.mascot.Mascot.apply(Unknown Source)
	at com.group_finity.mascot.Manager.tick(Unknown Source)
	at com.group_finity.mascot.Manager.access$000(Unknown Source)
	at com.group_finity.mascot.Manager$2.run(Unknown Source)
```

```
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: libjawt.so: cannot open shared object file: No such file or directory
	at com.sun.jna.Native.getWindowHandle0(Native Method)
	at com.sun.jna.Native$AWT.getComponentID(Native.java:1766)
	at com.sun.jna.Native$AWT.getWindowID(Native.java:1742)
	at com.sun.jna.Native.getWindowID(Native.java:242)
	at com.group_finity.mascot.x11.X11TranslucentWindow.updateX11(Unknown Source)
	at com.group_finity.mascot.x11.X11TranslucentWindow.updateImage(Unknown Source)
	at com.group_finity.mascot.Mascot.apply(Unknown Source)
	at com.group_finity.mascot.Manager.tick(Unknown Source)
	at com.group_finity.mascot.Manager.access$000(Unknown Source)
	at com.group_finity.mascot.Manager$2.run(Unknown Source)
```

**Comment by ShizukanaYaseotoko** [comment]
Same thing for me, sometimes it works, then blanks out after a while, sometimes just spawns a black window. The maintainer probably won't fix it though, considering the last update was 13 years ago...

**Comment by ShizukanaYaseotoko** [comment]
I just found out that using java 8 solves the exception, altho sometimes the window goes black anyway.
I installed the JRE with
sudo pacman -S jre8
then changed the path with
PATH=/usr/lib/jvm/java-8-jre/jre/bin/:$PATH
to make sure the launch.sh script picks up the old java first. Then launched the script, and voila!
